variables:  
  imageName: 'ml_issue'  # Replace with the name of the image you want to publish

trigger:
- master
- task: versioncounter@1
  inputs:
    VersionVariable: '1.0.*'
    DevOpsPat: 'lrurngirbq4odbemxjviadang653ecigzv33ovjdb5lx2vussjxa'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    docker build -t $(dockerId)/$(imageName) .
    docker login -u $(dockerId) -p $(pswd) <docker-registry-url>
  displayName: 'Run a multi-line script'
  env:
    pswd: $(dockerPassword)

  # Starter pipeline
- task: Docker@2
  inputs:
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
