variables:  
  imageName: 'ml_issue'  # Replace with the name of the image you want to publish

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml

    docker build -t $(dockerId)/$(imageName):$(Build.BuildNumber) .
    docker login -u $(dockerId) -p $(dockerPassword)
    docker push $(dockerId)/$(imageName):$(Build.BuildNumber)
  displayName: 'Docker pipeline'
  env:
    pswd: $(dockerPassword)

  # Starter Docker pipeline
  #- task: Docker@2
  # inputs:
  #  command: 'buildAndPush'
  #  Dockerfile: '**/Dockerfile'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
